### ISSUE TITLE
About CS3243 final cheat sheet

### ISSUE THREAD

**Issue by waynefong0401** [indocomsoft/nus-cheatsheets#1]
Hi Julius, this is Wayne from SoC. I have been using your Cheatsheets for my finals. Your sheets are really neat and professional. I really love them. I know this is kind of rude but is it possible for me to ask for the cheat sheet for CS3243 final? Thank you very much for providing the cheat sheets.

**Comment by indocomsoft** [comment]
It's up now! Sorry I don't really check my GitHub emails
